name: ONDO Rebound Bot

on:
  schedule:
    - cron: '*/10 * * * *'   # κάθε 10 λεπτά
  workflow_dispatch:         # επιτρέπει χειροκίνητη εκτέλεση

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # ενεργοποιεί το Node.js 24 για τα actions
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests yfinance pandas feedparser vaderSentiment

      - name: Run script
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          ENTER_LONG_MESSAGE: ${{ secrets.ENTER_LONG_MESSAGE }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
